<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<OutputType>exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<UserSecretsId>f4b0f324-d27b-4b47-8b4f-abb682788401</UserSecretsId>
		<!-- I'm disabling these since I'm concerned about performance on my free server :) -->
		<ServerGarbageCollection>false</ServerGarbageCollection>
		<ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NetCord" Version="1.0.0-beta.9" />
		<PackageReference Include="NetCord.Hosting" Version="1.0.0-beta.9" />
		<PackageReference Include="NetCord.Hosting.AspNetCore" Version="1.0.0-beta.9" />
		<PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-beta.9" />
		<PackageReference Include="NetCord.Services" Version="1.0.0-beta.9" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Database\Migrations\" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="word_pool.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
