// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WordOfTheDayBot.Database;

#nullable disable

namespace WordOfTheDayBot.Database.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260705000802_AddGuildIdAndDateOnlyAttempt1")]
partial class AddGuildIdAndDateOnlyAttempt1 {
	/// <inheritdoc />
	protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
		modelBuilder
			.HasDefaultSchema("wordbot")
			.HasAnnotation("ProductVersion", "10.0.9")
			.HasAnnotation("Relational:MaxIdentifierLength", 63);

		NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

		modelBuilder.Entity("WordOfTheDayBot.Database.SentWord", b => {
			b.Property<int>("Id")
				.ValueGeneratedOnAdd()
				.HasColumnType("integer");

			NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

			b.Property<DateTime>("EnterDateTimeUTC")
				.ValueGeneratedOnAdd()
				.HasColumnType("timestamp with time zone")
				.HasDefaultValueSql("timezone('utc', now())");

			b.Property<int?>("ServerId")
				.HasColumnType("integer");

			b.Property<string>("Word")
				.IsRequired()
				.HasColumnType("text");

			b.HasKey("Id");

			b.HasIndex("ServerId");

			b.ToTable("SentWords", "wordbot");
		});

		modelBuilder.Entity("WordOfTheDayBot.Database.Server", b => {
			b.Property<int>("Id")
				.ValueGeneratedOnAdd()
				.HasColumnType("integer");

			NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

			b.Property<decimal>("DiscordGuildId")
				.HasColumnType("numeric(20,0)");

			b.Property<DateTime>("EnterDateTimeUTC")
				.ValueGeneratedOnAdd()
				.HasColumnType("timestamp with time zone")
				.HasDefaultValueSql("timezone('utc', now())");

			b.Property<TimeOnly>("TimeToSendDailyWordUTC")
				.HasColumnType("time without time zone");

			b.HasKey("Id");

			b.HasIndex("DiscordGuildId")
				.IsUnique();

			b.ToTable("Servers", "wordbot");
		});

		modelBuilder.Entity("WordOfTheDayBot.Database.SentWord", b => {
			b.HasOne("WordOfTheDayBot.Database.Server", "Server")
				.WithMany()
				.HasForeignKey("ServerId");

			b.Navigation("Server");
		});
#pragma warning restore 612, 618
	}
}
